import { Heading, Box, Container, Text, Code, VStack } from "@chakra-ui/react";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box py="10">
          <Container maxW="3xl">
              <Heading>Task scheduler with XState</Heading>

              <Box borderWidth={1} p="4" mt="4">
                <Text>
                  Current state of the scheduler: <Code>idle</Code>
                </Text>
              </Box>
          </Container>
        </Box>
      </main>
    </>
  );
}
